version: "3.9"

services:
  server:
    command: npm run start:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server
    working_dir: /home/node/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/home/node/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    networks:
      - local
  database:
    image: postgres
    container_name: database
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

networks:
  local:
    driver: bridge
